{{- if .Values.ingress.enabled -}}
{{- $fullName := include "exploitableapp.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "exploitableapp.name" . }}
    chart: {{ template "exploitableapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts: 
    - {{ . }}
    secretName: exploitable-tls
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8080
          - path: "/guacamole/"
            backend:
              serviceName: guac-guacamole
              servicePort: 8080
  {{- end }}
{{- end }}
