{{- if .Values.ingress.enabled -}}
{{- $fullName := include "exploitableapp.fullname" . -}}
{{- $name := include "exploitableapp.name" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "exploitableapp.name" . }}
    chart: {{ template "exploitableapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.ingress.azureapprouting }}    
    kubernetes.io/ingress.class: "addon-http-application-routing"
  {{- else }}
    kubernetes.io/ingress.class: "nginx"
  {{- end }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts: 
    - {{ . }}
    secretName: {{ printf "%s.tls" . }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8080
          - path: "/guacamole/"
            backend:
              serviceName: {{ printf "%s-guacamole" $fullName | replace "web-" "guac-" }}
              servicePort: 8080
  {{- end }}
{{- end }}
