theme: jekyll-theme-minimal
title: Exploitable.App
description: A .NET Core Project for Web Pased Pen Testing
logo: https://github.com/postworthy/ExploitableApp/raw/master/ExploitableApp/wwwroot/images/businessman_512.png
google_analytics: UA-642235-16
