version: '3.4'

services:
  exploitableapp:
    image: ${DOCKER_REGISTRY}exploitableapp
    build:
      context: .
#      dockerfile: ExploitableApp\Dockerfile
      dockerfile: ./ExploitableApp/Dockerfile 
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"