version: '3.4'

volumes:
  sharedfiles: {}

services:
  proxy:
    ports:
      - "80:80"
  app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
  app3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    
  exploitableapp-ws:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sharedfiles:/app/sharedfiles/

networks:
  default:
    external:
      name: nat

