version: '3.4'

services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - app1
      - app2
      - app3
  app1:
    container_name: app1
    image: ${DOCKER_REGISTRY}exploitableapp
    build:
      context: .
      dockerfile: ./ExploitableApp/Dockerfile 
    depends_on:
      - db
      - exploitableapp-ws
  app2:
    container_name: app2
    image: ${DOCKER_REGISTRY}exploitableapp
    build:
      context: .
      dockerfile: ./ExploitableApp/Dockerfile 
    depends_on:
      - db
      - exploitableapp-ws
  app3:
    container_name: app3
    image: ${DOCKER_REGISTRY}exploitableapp
    build:
      context: .
      dockerfile: ./ExploitableApp/Dockerfile 
    depends_on:
      - db
      - exploitableapp-ws
  exploitableapp-ws:
    image: ${DOCKER_REGISTRY}exploitableappwebservice
    build:
      context: .
      dockerfile: ./ExploitableApp.WebService/Dockerfile
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
