version: '3.4'

services:
  app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  app3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    
  exploitableapp-ws:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sharedfiles: {}

networks:
  default:
    external:
      name: nat