version: '3'

services:
  proxy:
    image: exploitable/proxy:arm32v7
    ports:
      - "80:80"
      - "9000:9000"
    depends_on:
      - app1
      - app2
      - app3
      - exploitableapp-ws
      - netmon
    networks:
      main:
        aliases:
          - proxy
  app1:
    container_name: app1
    image: exploitable/exploitableapp:arm32v7
    depends_on:
      - db
      - exploitableapp-ws
      - redis
      - netmon
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - app1
  app2:
    container_name: app2
    image: exploitable/exploitableapp:arm32v7
    depends_on:
      - db
      - exploitableapp-ws
      - redis
      - netmon
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - app2
  app3:
    container_name: app3
    image: exploitable/exploitableapp:arm32v7
    depends_on:
      - db
      - exploitableapp-ws
      - redis
      - netmon
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - app3
  exploitableapp-ws:
    image: exploitable/exploitableapp.webservice:arm32v7
    depends_on:
      - db
      - netmon
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - exploitable-ws
  redis:
    image: "redis:4.0.11"
    command: redis-server --requirepass Password1
    depends_on:
      - netmon
    networks:
      main:
        aliases:
          - redis
  db:
    image: hypriot/rpi-mysql
    restart: always
    depends_on:
      - netmon
    volumes:
      - sharedfiles:/sharedfiles/
    environment:
      MYSQL_ROOT_PASSWORD: "Password1"
      MYSQL_DATABASE: "ExploitableDB"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Password1"
    networks:
      main:
        aliases:
          - db
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      main:
        aliases:
          - adminer
  netmon:
    image: exploitable/netmon:arm32v7
    volumes:
      - sharedfiles:/sharedfiles/
    ports:
      - "1337:22"
    networks:
      main:
        aliases:
          - netmon

volumes:
  sharedfiles: {}

networks:
  main: {}