version: '3'

services:
  proxy:
    container_name: proxy
    image: exploitable/exploitableapp:arm32v7
    depends_on:
      - db
      - exploitableapp-ws
      - redis
      - netmon
    ports:
      - "80:8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - proxy
  exploitableapp-ws:
    image: exploitable/exploitableapp.webservice:arm32v7
    depends_on:
      - db
      - netmon
    ports:
      - "8080"
    volumes:
      - sharedfiles:/app/sharedfiles/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      USEMYSQL: "true"
    networks:
      main:
        aliases:
          - exploitable-ws
  redis:
    image: "redis:4.0.11"
    command: redis-server --requirepass Password1
    depends_on:
      - netmon
    ports:
      - "6379"
    networks:
      main:
        aliases:
          - redis
  db:
    image: hypriot/rpi-mysql
    restart: always
    depends_on:
      - netmon
    volumes:
      - sharedfiles:/sharedfiles/
    environment:
      MYSQL_ROOT_PASSWORD: "Password1"
      MYSQL_DATABASE: "ExploitableDB"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "Password1"
    networks:
      main:
        aliases:
          - db
  netmon:
    image: exploitable/netmon:arm32v7
    volumes:
      - sharedfiles:/sharedfiles/
    ports:
      - "1337:22"
    networks:
      main:
        aliases:
          - netmon

volumes:
  sharedfiles: {}

networks:
  main: {}