apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" .Release.Name  "guacd" }}
    release: {{ .Release.Name }}
  name: {{ printf "%s-%s" .Release.Name  "guacd" }}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Release.Name  "guacd" }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name  "guacd" }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: {{ .Values.guacdImage }}
        name: {{ printf "%s-%s" .Release.Name  "guacd" }}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name  "guacd" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" .Release.Name  "guacd" }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: tcp
    port: 4822
    targetPort: 4822
  selector:
    app: {{ printf "%s-%s" .Release.Name  "guacd" }}
    release: {{ .Release.Name }}
