apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" .Release.Name  "guacamole" }}
    release: {{ .Release.Name }}
  name: {{ printf "%s-%s" .Release.Name  "guacamole" }}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Release.Name  "guacamole" }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name  "guacamole" }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: sharedscripts
        emptyDir: {}
      initContainers:
      - name: schemagen
        image: guacamole/guacamole
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sharedscripts
          mountPath: /tmp
        command:
        - /bin/bash
        - -c
        - '/opt/guacamole/bin/initdb.sh --postgres > /tmp/initdb.sql'
      - name: check-db-ready
        image: postgres:9.6.14-alpine
        imagePullPolicy: IfNotPresent
        command: 
        - sh
        - -c 
        - 'until pg_isready -h {{ printf "%s-%s" .Release.Name  "postgres" }} -p 5432; do echo waiting for database; sleep 2; done;'
      - name: execute
        image: postgres:9.6.14-alpine
        volumeMounts:
        - name: sharedscripts
          mountPath: /tmp
        command:
        - /bin/bash
        - -c
        - 'PGPASSWORD={{ .Values.postgresPwd }} psql -U {{ .Values.postgresUser }} -d {{ .Values.postgresDb }} -h {{ printf "%s-%s" .Release.Name  "postgres" }} -f /tmp/initdb.sql'
      containers:
      - env:
        - name: "GUACD_PORT"
          value: "4822"
        - name: "GUACD_HOSTNAME"
          value: "{{ printf "%s-%s" .Release.Name  "guacd" }}"
        - name: "POSTGRES_HOSTNAME"
          value: "{{ printf "%s-%s" .Release.Name  "postgres" }}"
        - name: "POSTGRES_PORT"
          value: "5432"
        - name: "POSTGRES_DATABASE"
          value: "{{ .Values.postgresDb }}"
        - name: "POSTGRES_PASSWORD"
          value: "{{ .Values.postgresPwd }}"
        - name: "POSTGRES_USER"
          value: "{{ .Values.postgresUser }}"
        image: {{ .Values.guacamoleImage }}
        imagePullPolicy: IfNotPresent
        name: {{ printf "%s-%s" .Release.Name  "guacamole" }}
        volumeMounts:
        - name: sharedscripts
          mountPath: /initdb
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name  "guacamole" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" .Release.Name  "guacamole" }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ printf "%s-%s" .Release.Name  "guacamole" }}
    release: {{ .Release.Name }}