apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacd" }}
  name: {{ printf "%s-%s" .Release.Name  "guacd" }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacd" }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: {{ .Values.guacdImage }}
        name: {{ printf "%s-%s" .Release.Name  "guacd" }}
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacd" }}
  name: {{ printf "%s-%s" .Release.Name  "guacd" }}
spec:
  ports:
  - name: "4822"
    port: 4822
    targetPort: 4822
  selector:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacd" }}
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" .Release.Name  "guacd-hpa" }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" .Release.Name  "guacd" }}
  minReplicas: 1
  maxReplicas: {{ .Values.maxServiceReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.averageServiceUtilization }}