apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ printf "%s-%s" .Release.Name  "guacamole-ingress" }}
  labels:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "guacamole-ingress" }}
  annotations:
    ingress.kubernetes.io/proxy-body-size: '0'
    ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/affinity: 'cookie'
    nginx.ingress.kubernetes.io/session-cookie-name: 'route'
    nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ printf "%s-%s" .Release.Name  "guacamole" }}
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - {}