apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "postgres" }} 
  name: {{ printf "%s-%s" .Release.Name  "postgres" }} 
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ printf "%s-%s" .Release.Name  "postgres" }} 
    spec:
      volumes:
      - name: sharedfiles
        emptyDir: {}
      - name: sharedscripts
        emptyDir: {}
      containers:
      - env:
        - name: "PGDATA"
          value: "/var/lib/postgresql/data/guacamole"
        - name: "POSTGRES_DB"
          value: "{{ .Values.postgresDb }}"
        - name: "POSTGRES_PASSWORD"
          value: "{{ .Values.postgresPwd }}"
        - name: "POSTGRES_USER"
          value: "{{ .Values.postgresUser }}"
        image: "postgres:9.6.14-alpine"
        volumeMounts:
        - name: sharedfiles
          mountPath: /var/lib/postgresql/data
        - name: sharedscripts
          mountPath: /docker-entrypoint-initdb.d/
        name: "{{ printf "%s-%s" .Release.Name  "postgres" }}"
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "postgres" }} 
  name: {{ printf "%s-%s" .Release.Name  "postgres" }} 
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: {{ printf "%s-%s" .Release.Name  "postgres" }} 
status:
  loadBalancer: {}