apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "db.name" . }}
    helm.sh/chart: {{ include "db.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "db.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "db.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: netmon
          image: exploitable/netmon:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
        - name: {{ include "db.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
            - name: postgres
              containerPort: 5432
              protocol: TCP              
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Password1"
            - name: MYSQL_DATABASE
              value: "ExploitableDB"
            - name: MYSQL_USER
              value: "sa"
            - name: MYSQL_PASSWORD
              value: "Password1"
            - name: "PGDATA"
              value: "/var/lib/postgresql/data/exploitable"
            - name: "POSTGRES_DB"
              value: "ExploitableDB"
            - name: "POSTGRES_PASSWORD"
              value: "Password1"
            - name: "POSTGRES_USER"
              value: "sa"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
