apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "db.name" . }}
    helm.sh/chart: {{ include "db.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
