apiVersion: v1
kind: Service
metadata:
  name: {{ template "exploitableappwebservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "exploitableappwebservice.name" . }}
    chart: {{ template "exploitableappwebservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "exploitableappwebservice.name" . }}
    release: {{ .Release.Name }}
