service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - kibana.attlocal.net
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

backendServiceName: elastic-kibana
nameOverride: elasticsearch